### ISSUE TITLE
Click Event Fired Twice

### ISSUE THREAD

**Issue by melloware** [microneer/jquery.tabSlideOut.js#5] opened 2016-11-30 20:24 UTC
Check out this JSFiddle 

http://jsfiddle.net/xLow0hxh/

Click the button you will see the Right tab open then close.    It is related to this..

http://stackoverflow.com/questions/25264726/why-is-the-onclick-event-triggered-twice

But I can't seem to figure out the right place in the JS to fix this.

**Comment by microneer** [comment] 2016-12-01 06:46
I think the problem is actually that option clickScreenToClose is true by default - so when your button is clicked the panel opens, but the library has attached to the window to detect the clickScreenToClose and receives the click too, sees it is open, and decides to close it. Hmm...

As a workaround you could set clickScreenToClose to false for #right. But not ideal.

**Closed as completed** 2016-12-01 07:25 UTC

**Comment by microneer** [comment] 2016-12-01 07:34
If you convince your browser to reload the tabSlideOut.js from rawgit, you should find your JSFiddle is fixed. Thanks for the bug report.

**Comment by melloware** [comment] 2016-12-01 13:07
Thanks for fixing!
